[package]
name = "qcl-compiler"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
z3.workspace = true
egg.workspace = true
pest.workspace = true
pest_derive.workspace = true
petgraph.workspace = true
rustc-hash.workspace = true
indexmap.workspace = true
clap.workspace = true
ariadne.workspace = true
codespan-reporting.workspace = true

# Cranelift Native IR lowering
cranelift-codegen.workspace = true
cranelift-wasm.workspace = true
